steps:
  # Docker Build
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "europe-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/v2g-server:$SHORT_SHA",
        ".",
      ]
    # Docker push to Google Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "europe-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/v2g-server:$SHORT_SHA",
      ]
  # Deploy to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "v2g-server",
        "europe-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/v2g-server:$SHORT_SHA",
        "--region",
        "europe-west4",
        "--platform",
        "managed",
      ]
